# Generated by Django 3.0.7 on 2020-11-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20201110_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='level_id',
            new_name='level',
        ),
    ]
