# Generated by Django 5.1.1 on 2024-09-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20240919_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoptime',
            old_name='continuous_dropoff',
            new_name='continuous_drop_off',
        ),
    ]
