# Generated by Django 5.1.1 on 2024-09-27 03:26

import rest_api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_rename_continuous_dropoff_stoptime_continuous_drop_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptime',
            name='arrival_time',
            field=rest_api.models.GTFSDurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='departure_time',
            field=rest_api.models.GTFSDurationField(blank=True, null=True),
        ),
    ]
