# Generated by Django 3.0.7 on 2020-11-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20201111_0925'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pathway',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='project',
        ),
    ]
