# Generated by Django 5.1.1 on 2024-10-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_rename_continuous_dropoff_stoptime_continuous_drop_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
