# Generated by Django 5.1.1 on 2025-01-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_alter_route_route_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='loading_gtfs_error_message',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
