# Generated by Django 5.1.1 on 2025-02-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_alter_project_loading_gtfs_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
