# Generated by Django 3.0.7 on 2020-11-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_transfer_min_transfer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='fareattribute',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Agency'),
        ),
        migrations.AlterField(
            model_name='fareattribute',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='farerule',
            name='fare_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.FareAttribute'),
        ),
        migrations.AlterField(
            model_name='farerule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Route'),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Trip'),
        ),
        migrations.AlterField(
            model_name='level',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='from_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_from', to='rest_api.Stop'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_to', to='rest_api.Stop'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publishing_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.PublishingURL'),
        ),
        migrations.AlterField(
            model_name='publishingurl',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='route',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Agency'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Stop'),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Trip'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_stop', to='rest_api.Stop'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_stop', to='rest_api.Stop'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Project'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.Route'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rest_api.Shape'),
        ),
    ]
