# Generated by Django 5.1.1 on 2025-02-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_stop_stop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_lon',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
