# Generated by Django 3.0.7 on 2020-11-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20201112_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_timezone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
