# Generated by Django 5.1.1 on 2025-02-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_alter_stop_stop_lat_alter_stop_stop_lon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together=set(),
        ),
    ]
