# Generated by Django 5.1.1 on 2025-02-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_alter_transfer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_lon',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
