# Generated by Django 5.1.1 on 2026-06-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_alter_stop_stop_lat_alter_stop_stop_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_lang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_timezone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='service_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='service_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fareattribute',
            name='currency_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fareattribute',
            name='fare_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='feed_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='feed_lang',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='feed_publisher_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='feed_version',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='pathway_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='shape_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stop',
            name='zone_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='stop_headsign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='block_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='service_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
