# Generated by Django 3.1.3 on 2020-11-15 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_auto_20201112_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTFSValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('finished', 'Finished'), ('error', 'Error'), ('canceled', 'Canceled')], default=None, max_length=20, null=True)),
                ('ran_at', models.DateTimeField(default=None, null=True)),
                ('error_message', models.TextField(default=None, null=True)),
                ('error_number', models.IntegerField(default=None, null=True)),
                ('warning_number', models.IntegerField(default=None, null=True)),
                ('duration', models.DurationField(default=None, null=True)),
                ('job_id', models.UUIDField(null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project')),
            ],
        ),
    ]
