# Generated by Django 3.1.3 on 2020-11-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_auto_20201115_0113'),
        ('rest_api', '0012_auto_20201113_1050'),
    ]

    operations = [
    ]
