# Generated by Django 3.1.3 on 2020-11-19 03:37

from django.db import migrations, models
import rest_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_merge_20201116_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gtfs_file',
            field=models.FileField(null=True, upload_to=rest_api.models.gtfs_update_to),
        ),
    ]
