# Generated by Django 3.1.3 on 2020-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0016_project_last_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gtfs_file_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
