# Generated by Django 3.1.3 on 2020-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_project_gtfs_file_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
