# Generated by Django 3.1.3 on 2020-11-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0020_project_gtfs_creation_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gtfs_creation_duration',
        ),
    ]
