# Generated by Django 3.1.3 on 2020-12-07 04:43

from django.db import migrations, models
import rest_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0022_project_gtfs_creation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='envelope',
            field=models.JSONField(default=rest_api.models.get_empty_envelope),
        ),
    ]
