# Generated by Django 3.1.3 on 2021-01-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_project_envelope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptime',
            name='arrival_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='departure_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_times', to='rest_api.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='stoptime',
            unique_together={('trip', 'stop_sequence')},
        ),
    ]
