# Generated by Django 3.1.3 on 2021-02-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0025_auto_20210210_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='building_and_validation_job_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gtfs_validation_duration',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gtfs_validation_error_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gtfs_validation_message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gtfs_validation_warning_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='gtfs_creation_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('building', 'Building'), ('validating', 'Validating'), ('finished', 'Finished'), ('error', 'Error'), ('canceled', 'Canceled')], default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='GTFSValidation',
        ),
    ]
