# Generated by Django 3.1.3 on 2021-02-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_auto_20210211_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gtfs_creation_duration',
            new_name='gtfs_building_duration',
        ),
    ]
