# Generated by Django 3.1.3 on 2021-02-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0027_auto_20210213_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gtfs_creation_status',
            new_name='gtfs_building_and_validation_status',
        ),
    ]
