# Generated by Django 3.1.3 on 2021-02-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0029_project_creation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='loading_gtfs_error_message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
