# Generated by Django 3.1.3 on 2021-02-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0030_project_loading_gtfs_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='loading_gtfs_error_message',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
