# Generated by Django 3.1.3 on 2021-02-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0034_auto_20210216_1649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publishingurl',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='publishingurl',
            name='project',
        ),
        migrations.AlterField(
            model_name='agency',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project'),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project'),
        ),
        migrations.AlterField(
            model_name='fareattribute',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project'),
        ),
        migrations.AlterField(
            model_name='level',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project'),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='PublishingURL',
        ),
    ]
