# Generated by Django 3.1.3 on 2021-02-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0035_auto_20210226_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinfo',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.project'),
        ),
    ]
