# Generated by Django 3.1.3 on 2021-02-28 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0037_auto_20210226_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='direction_id',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
