# Generated by Django 3.1.3 on 2021-02-28 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0038_auto_20210228_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='bikes_allowed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='wheelchair_accessible',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
