# Generated by Django 3.1.3 on 2021-03-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0039_auto_20210228_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='loading_gtfs_job_id',
            field=models.UUIDField(null=True),
        ),
    ]
