# Generated by Django 3.1.3 on 2021-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0041_auto_20210304_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gtfs_validation_message',
            field=models.TextField(default=''),
        ),
    ]
