# Generated by Django 3.2.4 on 2022-01-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0041_auto_20210304_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapepoint',
            name='shape_dist_traveled',
            field=models.FloatField(default=None, null=True),
        ),
    ]
