# Generated by Django 3.2.4 on 2022-01-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0042_shapepoint_shape_dist_traveled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='exact_times',
            field=models.IntegerField(null=True),
        ),
    ]
