# Generated by Django 4.2.8 on 2024-01-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0042_shapepoint_shape_dist_traveled'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_confirmation_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('session_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('email_recovery_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_api.user'),
            preserve_default=False,
        ),
    ]
