# Generated by Django 3.2.4 on 2022-04-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0043_alter_frequency_exact_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
