# Generated by Django 3.2.4 on 2022-04-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0044_alter_route_route_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_headsign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
