# Generated by Django 3.2.4 on 2022-08-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0046_alter_project_loading_gtfs_error_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoptime',
            old_name='continuous_dropoff',
            new_name='continuous_drop_off',
        ),
    ]
