# Generated by Django 3.2.24 on 2026-08-25 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0047_rename_continuous_dropoff_stoptime_continuous_drop_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptime',
            name='dist_to_next_m',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='wheelchair_boarding',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
