x-logging:
  &logging-defaults
  driver: json-file
  options:
    max-size: 50m
x-common: &common
  profiles:
    - default
    - prod
    - dev
x-django-settings:
  &django-settings
  <<: *common
  build:
    context: ..
    dockerfile: docker/Dockerfile
  volumes:
    - static_volume:/app/static
    - media_volume:/app/media
  env_file:
    - ./docker_env
    - ./dd_env
  restart: on-failure
  depends_on:
    - db
    - cache
  logging: *logging-defaults
services:
  datadog-agent:
    image: datadog/agent:latest
    shm_size: '2gb'
    profiles:
      - prod
    environment:
      - DD_APM_ENABLED=true
      - DD_HOSTNAME=gtfs-editor-host
      - DD_ENV=gtfs-editor
    env_file:
      - ../.dd.env.production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - nginx_network
      - database_network
      - cache_network
    restart: on-failure
    logging: *logging-defaults
  web:
    <<: *django-settings
    command: webserver
    networks:
      - nginx_network
      - database_network
      - cache_network
    environment:
      - DD_SERVICE=web
  worker:
    <<: *django-settings
    networks:
      - database_network
      - cache_network
    command: worker
    environment:
      - DD_SERVICE=worker
  nginx:
    <<: *common
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
      target: prod
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ../dhparam:/etc/ssl/certs
      - web-root:/var/www/html
    depends_on:
      - web
    networks:
      - nginx_network
  cache:
    profiles:
      - default
      - prod
      - dev
      - test
    image: redis:latest
    networks:
      - cache_network
  db:
    profiles:
      - default
      - prod
      - dev
      - test
    image: postgres:16.1-alpine
    volumes:
      - postgres_gtfseditor_data_v16:/var/lib/postgresql/data/
    env_file:
      - ./docker_db_env
    networks:
      - cache_network
      - database_network
  test:
    <<: *django-settings
    command: test
    profiles:
      - test
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./docker_env
    depends_on:
      - db
      - cache
    networks:
      - database_network
      - cache_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
  cache_network:
    driver: bridge

volumes:
  postgres_gtfseditor_data_v16:
  static_volume:
  media_volume:
  certbot-etc:
  certbot-var:
  web-root:
