services:
  web:
    command:
      - webserver-dev
    volumes:
      - ../:/app

  nginx:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
      target: dev
    ports:
      - "8000:80"

  db:
    ports:
      - "5431:5432"