version: '3.7'

services:
  web:
    command:
      - webserver-dev
    ports:
      - "8001:8000"
    volumes:
      - ../:/app
  db:
    ports:
      - "5432:5432"
  cache:
    ports:
      - "6379:6379"