services:
  nginx-certbot:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
      target: certbot
    profiles: [ 'certbot' ]
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    ports:
      - "80:80"
  certbot:
    profiles: ['certbot']
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-certbot
    command: certonly --webroot --webroot-path=/var/www/html --email dgarcia@transapp.cl --agree-tos --no-eff-email -d gtfseditor.transapp.cl -d www.gtfseditor.transapp.cl -d gtfs-editor.transapp.cl -d www.gtfs-editor.transapp.cl --force-renewal