# Generated by Django 4.2.8 on 2024-01-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_confirmation_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('session_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('email_recovery_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
