# Generated by Django 4.2.8 on 2024-01-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
