# Generated by Django 4.2.8 on 2024-01-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_confirmation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_recovery_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
